Add bookings
EvgeniPolyakov/java-shareit pull request #3
Opened 2022-08-29 21:02 UTC by EvgeniPolyakov

2022-08-31 10:13 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    private static final String USER_HEADER = "X-Sharer-User-Id";
константы должны быть выше остальных полей

2022-08-31 10:14 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public List<Booking> getAllByBooker(@RequestHeader(USER_HEADER) Long userId,
контроллеры должны возвращать dto объекты

2022-08-31 10:15 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public Booking findById(@PathVariable("id") Long id, @RequestHeader(USER_HEADER) Long userId) {
id можно вынести в константу `ID_PATH_VARIABLE_KEY`

2022-08-31 10:28 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        return bookingService.save(booking, userId);
у bookingService метод лучше назвать book(), потому что save обычно означает просто сохранение каких-то данных, а тут это все таки операция бронирования

2022-08-31 10:41 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/model/OutgoingBookingDto.java
> +    private Long id;
тут тоже бы в название добавить, что это за id
`bookingId`

2022-08-31 10:43 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/model/Status.java
> +    PAST,
такие значения как ALL, PAST, FUTURE смущают, потому что трудно понять, что за ситуация с бронированием, когда у него такой статус

лучше разделить статусы бронирования и статусы-фильтры для поиска

2022-08-31 10:44 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +                                                                               LocalDateTime start, LocalDateTime end);
если аргументы переносятся на другую строку, то стоит каждый перенести на отдельную

2022-08-31 10:50 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    private static final String STATUS_VALUE_ALL = "ALL";
у значений енумов можно получать строковое представление через метод name()
`Status.ALL.name()`

тогда эти константы будут не нужны

2022-08-31 10:54 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (!booking.getItem().getOwner().getId().equals(userId)) {
можно объединить условия в один if и использовать так:

`return (booking != null && booking.getItem().getOwner().getId().equals(userId)) ? booking : null;`

2022-08-31 10:55 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (status) {
из такого названия переменной непонятно, что означает status == true/false, надо дать более понятное имя

2022-08-31 10:55 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (status) {
например `isBookingApproved`

2022-08-31 10:58 UTC, makholin commented on src/main/java/ru/practicum/shareit/common/ValidationService.java
> +        log.info(VALIDATION_STAGE_MESSAGE);
тут лучше использовать не общий шаблон сообщения, а уникальное сообщение для каждого типа валидации
и в целом, константы для сообщений обычно не используются, потому что для каждого кейса обычно нужно отдельное уникальное сообщение, чтобы не спутать

2022-08-31 11:02 UTC, makholin requested changes
Нужно исправить замечания

2022-08-31 22:20 UTC, EvgeniPolyakov commented on src/main/java/ru/practicum/shareit/booking/model/OutgoingBookingDto.java
> +    private Long id;
К сожалению, тесты в постмановской коллекции ждут при проверке тут именно поле id.

2022-09-02 08:27 UTC, makholin approved these changes
Работа принята

2022-09-02 10:54 UTC, merged